kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: {{ salt['config.get']('k8s-common-config:encryption_key') }}
      - identity: {}
